# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_auto_20170910_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
